export HOMEBREW_PREFIX=/opt/homebrew

export PATH="${HOMEBREW_PREFIX}/opt/openssl/bin:$PATH"

export PATH=$HOME/.local/bin:$PATH
export GPG_TTY=$(tty)

source ${HOMEBREW_PREFIX}/opt/antidote/share/antidote/antidote.zsh
antidote load
